### ISSUE TITLE
URL istituzionale

### ISSUE THREAD

**Issue by davideriboli** [ABA-Sironi-Codex/.github#2]
Voltare i DNS per far puntare codex.accademiasironi.it sul deploy del repository.

**Comment by xdade** [comment]
@davideriboli a quale indirizzo deve puntare codex.accademiasironi.it ?

**Comment by davideriboli** [comment]
Saperlo : ) : )  :)

Ora tento il primo deploy serio e ti faccio sapere. Probabilmente la risposta definitiva ti arriva nel primo dopopranzo.
